default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: series_development

test:
  <<: *default
  database: series_test

production:
  <<: *default
  database: series_production
  username: series
  password: <%= ENV['SERIES_DATABASE_PASSWORD'] %>
